#!/usr/bin/env bash
# Install openconnect + vpnc-scripts + sudoers rule for Argos Settings → GlobalProtect VPN.
#
# Idempotent — safe to re-run. Installs on the current host (auto-detects user).
# Does NOT persist credentials — the UI collects portal/user/password at connect time.
#
# Plan: ~/.claude/plans/ok-now-fix-the-smooth-mango.md
# Docs: https://www.infradead.org/openconnect/manual.html
#
# Usage:
#   sudo ./scripts/ops/install-globalprotect.sh
#
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────

if [[ -n "${SUDO_USER:-}" && "$SUDO_USER" != "root" ]]; then
    ARGOS_USER="$SUDO_USER"
elif [[ -n "${SUDO_UID:-}" ]]; then
    ARGOS_USER="$(getent passwd "$SUDO_UID" | cut -d: -f1)"
else
    REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
    ARGOS_USER="$(stat -c '%U' "$REPO_ROOT")"
fi

if [[ -z "$ARGOS_USER" || "$ARGOS_USER" == "root" ]]; then
    echo "[-] Could not determine non-root Argos user. Re-run via 'sudo' from that user's session." >&2
    exit 1
fi

info() { printf '[+] %s\n' "$*"; }
step() { printf '\n=== %s ===\n' "$*"; }
err()  { printf '[-] %s\n' "$*" >&2; exit 1; }

# ─────────────────────────────────────────────────────────────────────────────
# 1. Packages
# ─────────────────────────────────────────────────────────────────────────────

step "PACKAGES"

if ! command -v openconnect >/dev/null 2>&1; then
    info "Installing openconnect + vpnc-scripts"
    apt-get update -q
    apt-get install -y -q openconnect vpnc-scripts
else
    info "openconnect already installed ($(openconnect --version 2>&1 | head -1))"
fi

# Sanity: openconnect must support the GlobalProtect protocol.
if ! openconnect --help 2>&1 | grep -q 'gp for'; then
    err "Installed openconnect does not advertise --protocol=gp support. Upgrade required."
fi

OC_BIN="$(command -v openconnect)"
info "openconnect binary: $OC_BIN"

# The service code expects /usr/sbin/openconnect. Warn loudly if packaging moved it.
if [[ "$OC_BIN" != "/usr/sbin/openconnect" ]]; then
    err "openconnect is at $OC_BIN but service expects /usr/sbin/openconnect — update OC_BIN in src/lib/server/services/globalprotect/globalprotect-service.ts"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 2. Sudoers rule
# ─────────────────────────────────────────────────────────────────────────────

step "SUDOERS"

SUDOERS_TMP="/etc/sudoers.d/argos-globalprotect.new"
SUDOERS_FINAL="/etc/sudoers.d/argos-globalprotect"

cat > "$SUDOERS_TMP" <<EOF
# Argos — GlobalProtect VPN (openconnect) lifecycle control
# Generated by scripts/ops/install-globalprotect.sh — do not edit by hand.
$ARGOS_USER ALL=(root) NOPASSWD: /usr/sbin/openconnect *
$ARGOS_USER ALL=(root) NOPASSWD: /usr/bin/killall openconnect
EOF
chmod 0440 "$SUDOERS_TMP"
chown root:root "$SUDOERS_TMP"

if visudo -cf "$SUDOERS_TMP" >/dev/null; then
    mv "$SUDOERS_TMP" "$SUDOERS_FINAL"
    info "Installed $SUDOERS_FINAL"
else
    rm -f "$SUDOERS_TMP"
    err "sudoers syntax check failed — bailing."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 3. Smoke test
# ─────────────────────────────────────────────────────────────────────────────

step "SMOKE TEST"

if sudo -n -u "$ARGOS_USER" sudo -n /usr/sbin/openconnect --version >/dev/null 2>&1; then
    info "NOPASSWD rule verified — $ARGOS_USER can run openconnect without prompt."
else
    err "NOPASSWD verification failed — $ARGOS_USER cannot run openconnect via sudo -n."
fi

info "GlobalProtect VPN support installed. Restart argos-final to pick up code changes."
