/**
 * Tests for the gnss-sdr config generator.
 *
 * Pure function — covers default L1-only output, multi-constellation
 * upgrade, B205 hardware-bound validation, and idempotency.
 */

import { describe, expect, it } from 'vitest';

import { generateGnssSdrConf, resolveConfig } from './gnss-sdr-config-generator';

describe('resolveConfig', () => {
	it('returns L1-only defaults when no options passed', () => {
		const cfg = resolveConfig();
		expect(cfg.constellations).toBe('L1_GPS_ONLY');
		expect(cfg.sampleRate).toBe(4_000_000);
		expect(cfg.gain).toBe(50);
		expect(cfg.freq).toBe(1_575_420_000);
	});

	it('bumps default sampleRate to 8 MS/s when MULTI_L1', () => {
		const cfg = resolveConfig({ constellations: 'MULTI_L1' });
		expect(cfg.sampleRate).toBe(8_000_000);
	});

	it('honors explicit sampleRate + gain overrides', () => {
		const cfg = resolveConfig({ sampleRate: 2_500_000, gain: 65 });
		expect(cfg.sampleRate).toBe(2_500_000);
		expect(cfg.gain).toBe(65);
	});

	it('rejects sampleRate above B205 ADC ceiling (61.44 MS/s)', () => {
		expect(() => resolveConfig({ sampleRate: 70_000_000 })).toThrow(/sampleRate/);
	});

	it('rejects sampleRate ≤ 0', () => {
		expect(() => resolveConfig({ sampleRate: 0 })).toThrow(/sampleRate/);
		expect(() => resolveConfig({ sampleRate: -100 })).toThrow(/sampleRate/);
	});

	it('rejects gain outside [0, 76] for B205 AD9364', () => {
		expect(() => resolveConfig({ gain: -1 })).toThrow(/gain/);
		expect(() => resolveConfig({ gain: 77 })).toThrow(/gain/);
	});
});

describe('generateGnssSdrConf', () => {
	it('emits a header line + GNSS-SDR section + UHD SignalSource (no device_address)', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/generated by Argos gnss-sdr-config-generator/);
		expect(out).toMatch(/^\[GNSS-SDR\]$/m);
		expect(out).toMatch(/SignalSource\.implementation=UHD_Signal_Source/);
		// v0.0.21 wraps device_address as UHD addr= (Ethernet). For USB B-series we
		// rely on device_serial (only emitted when caller passes options.deviceSerial).
		expect(out).not.toMatch(/SignalSource\.device_address=/);
	});

	it('emits SignalSource.device_serial when deviceSerial option is passed', () => {
		const out = generateGnssSdrConf({ deviceSerial: '329F4D0' });
		expect(out).toMatch(/SignalSource\.device_serial=329F4D0/);
	});

	it('uses B205mini canonical subdev `A:A` (UHD AssertionError on `A:0`)', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/SignalSource\.subdevice=A:A/);
		expect(out).not.toMatch(/SignalSource\.subdevice=A:0/);
	});

	it('uses GPS L1 frequency 1575420000', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/SignalSource\.freq=1575420000/);
	});

	it('L1-only default has 8 GPS L1 channels + 8 in_acquisition + 0 others', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/Channels_1C\.count=8/);
		expect(out).toMatch(/Channels_1B\.count=0/);
		expect(out).toMatch(/Channels_1G\.count=0/);
		expect(out).toMatch(/Channels\.in_acquisition=8/);
	});

	it('MULTI_L1 enables 8 Galileo + 8 GLONASS channels + their acquisition blocks', () => {
		const out = generateGnssSdrConf({ constellations: 'MULTI_L1' });
		expect(out).toMatch(/Channels_1B\.count=8/);
		expect(out).toMatch(/Channels_1G\.count=8/);
		expect(out).toMatch(/Acquisition_1B\.implementation=Galileo_E1_PCPS/);
		expect(out).toMatch(/Acquisition_1G\.implementation=GLONASS_L1_CA_PCPS/);
	});

	it('uses pfa (canonical) not raw threshold for L1 acquisition', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/Acquisition_1C\.pfa=0\.01/);
		expect(out).not.toMatch(/Acquisition_1C\.threshold=/);
	});

	it('Monitor uses canonical `decimator_factor` spelling (not `decimation_factor`)', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/Monitor\.decimator_factor=50/);
		expect(out).not.toMatch(/Monitor\.decimation_factor=/);
	});

	it('PVT block emits NMEA to the Argos fifo + opens RTCM TCP server on 2101', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/PVT\.implementation=RTKLIB_PVT/);
		expect(out).toMatch(/PVT\.flag_rtcm_server=true/);
		expect(out).toMatch(/PVT\.rtcm_tcp_port=2101/);
		expect(out).toMatch(/PVT\.nmea_dump_filename=\/tmp\/argos-gnss-sdr\.nmea/);
		expect(out).toMatch(/PVT\.nmea_dump_enabled=true/);
	});

	it('Monitor block exposes UDP protobuf telemetry on 1234', () => {
		const out = generateGnssSdrConf();
		expect(out).toMatch(/Monitor\.enable_monitor=true/);
		expect(out).toMatch(/Monitor\.udp_port=1234/);
	});

	it('is byte-stable across runs (idempotent)', () => {
		const a = generateGnssSdrConf({ gain: 55 });
		const b = generateGnssSdrConf({ gain: 55 });
		expect(a).toBe(b);
	});
});
