/**
 * Generate the `gnss-sdr.conf` consumed by `gnss-sdr --config_file=...`.
 *
 * Output cribs from the canonical upstream recipe at
 * `conf/RealTime_input/gnss-sdr_GPS_L1_USRP_realtime.conf` in the gnss-sdr
 * repo: an empty `SignalSource.device_address` lets UHD auto-discover the
 * B205mini over USB without us hard-coding a serial number.
 *
 * The default L1-only config matches Argos's user-locked plan decision
 * (2026-05-27): fastest first fix, ~70% CPU on Jetson Orin, the operator
 * opts into multi-constellation explicitly via the advanced form.
 */

import {
	type ConstellationSet,
	GNSS_SDR_CONF_DIR,
	GNSS_SDR_MONITOR_UDP_PORT,
	GNSS_SDR_NMEA_FIFO,
	GNSS_SDR_RTCM_PORT,
	type GnssSdrStartOptions
} from './gnss-sdr-vnc-types';

// B205mini hardware bounds — mirror of the file-local constants in
// src/lib/server/spectrum/b205-source.ts:46-47. Those are not exported, so we
// duplicate the (immutable, vendor-defined) values here rather than touch
// the spectrum module just for two consts.
const B205_MIN_FREQ_HZ = 70_000_000;
const B205_MAX_FREQ_HZ = 6_000_000_000;

/** GPS L1 carrier frequency in Hz. */
const GPS_L1_FREQ_HZ = 1_575_420_000;

/** B205mini ADC ceiling per the Ettus B2x0 manual. */
const B205_MAX_SAMPLE_RATE = 61_440_000;

const DEFAULT_SAMPLE_RATE_L1 = 4_000_000;
const DEFAULT_SAMPLE_RATE_MULTI = 8_000_000;
const DEFAULT_GAIN_DB = 50;
const MIN_GAIN_DB = 0;
const MAX_GAIN_DB = 76;

/** Path to the generated config file. */
export const GENERATED_CONF_PATH = `${GNSS_SDR_CONF_DIR}/gnss-sdr.conf`;

/** Resolved knobs after merging caller options with defaults. */
export interface ResolvedConfig {
	constellations: ConstellationSet;
	sampleRate: number;
	gain: number;
	freq: number;
	deviceSerial: string | null;
}

/**
 * Resolve caller-supplied {@link GnssSdrStartOptions} against defaults and
 * validate against B205 hardware bounds. Pure — easy to unit-test.
 */
// eslint-disable-next-line complexity
export function resolveConfig(options: GnssSdrStartOptions = {}): ResolvedConfig {
	const constellations: ConstellationSet = options.constellations ?? 'L1_GPS_ONLY';
	const sampleRate =
		options.sampleRate ??
		(constellations === 'L1_GPS_ONLY' ? DEFAULT_SAMPLE_RATE_L1 : DEFAULT_SAMPLE_RATE_MULTI);
	const gain = options.gain ?? DEFAULT_GAIN_DB;

	if (GPS_L1_FREQ_HZ < B205_MIN_FREQ_HZ || GPS_L1_FREQ_HZ > B205_MAX_FREQ_HZ) {
		throw new Error(`GPS L1 frequency ${GPS_L1_FREQ_HZ} Hz outside B205 range`);
	}
	if (sampleRate <= 0 || sampleRate > B205_MAX_SAMPLE_RATE) {
		throw new Error(
			`sampleRate ${sampleRate} sps outside (0, ${B205_MAX_SAMPLE_RATE}] for B205mini`
		);
	}
	if (gain < MIN_GAIN_DB || gain > MAX_GAIN_DB) {
		throw new Error(
			`gain ${gain} dB outside [${MIN_GAIN_DB}, ${MAX_GAIN_DB}] for B205mini AD9364`
		);
	}

	const deviceSerial = options.deviceSerial?.trim() || null;

	return {
		constellations,
		sampleRate,
		gain,
		freq: GPS_L1_FREQ_HZ,
		deviceSerial
	};
}

/**
 * Build the configuration text. Mirrors the canonical upstream USRP recipe
 * with Argos-specific overrides for the NMEA fifo and the gpsd-bridge RTCM
 * port. The PVT block emits NMEA to {@link GNSS_SDR_NMEA_FIFO}, which the
 * socat bridge tails and forwards to gpsd on TCP {@link GNSS_SDR_NMEA_BRIDGE_PORT}.
 */
// eslint-disable-next-line max-lines-per-function, complexity
export function generateGnssSdrConf(options: GnssSdrStartOptions = {}): string {
	const cfg = resolveConfig(options);
	// Doc canonical (my-first-fix, conf/RealTime_input/USRP_realtime, monitoring tutorial):
	// 8 channels per constellation, 8 in_acquisition (parallel SV search across all
	// channels = faster first fix).
	const channels1cCount = 8;
	const channels1bCount = cfg.constellations === 'L1_GPS_ONLY' ? 0 : 8;
	const channels1gCount = cfg.constellations === 'L1_GPS_ONLY' ? 0 : 8;
	const channelsInAcquisition = channels1cCount;
	const internalFs = Math.min(cfg.sampleRate, 4_000_000);

	const lines: string[] = [
		'; gnss-sdr.conf — generated by Argos gnss-sdr-config-generator.ts. Do not edit by hand.',
		'[GNSS-SDR]',
		'',
		'; ─── global ────────────────────────────────────────────────────────',
		`GNSS-SDR.internal_fs_sps=${internalFs}`,
		'',
		'; ─── signal source — B205mini via UHD ──────────────────────────────',
		'; v0.0.21 wraps SignalSource.device_address as UHD addr= (Ethernet IP),',
		'; so for USB-attached B-series radios we use SignalSource.device_serial',
		'; instead — that populates UHD serial= which targets a specific USB',
		'; device without triggering the X300 Ethernet auto-probe (which itself',
		'; does a DNS lookup that aborts gnss-sdr when no DNS is reachable).',
		'SignalSource.implementation=UHD_Signal_Source',
		...(cfg.deviceSerial ? [`SignalSource.device_serial=${cfg.deviceSerial}`] : []),
		'SignalSource.item_type=gr_complex',
		`SignalSource.sampling_frequency=${cfg.sampleRate}`,
		`SignalSource.freq=${cfg.freq}`,
		`SignalSource.gain=${cfg.gain}`,
		'; B205mini exposes the RX daughterboard as `A:A` (UHD enumerates the single',
		'; ADC slot as channel A on board A). `A:0` is the USRP1 convention and will',
		'; trip an AssertionError on B-series radios — verified live 2026-05-27.',
		'SignalSource.subdevice=A:A',
		'SignalSource.samples=0',
		'SignalSource.repeat=false',
		'SignalSource.enable_throttle_control=false',
		'',
		'; ─── conditioner (pass through; we already requested L1 baseband) ──',
		'SignalConditioner.implementation=Pass_Through',
		'',
		'; ─── channels ──────────────────────────────────────────────────────',
		`Channels_1C.count=${channels1cCount}`,
		`Channels_1B.count=${channels1bCount}`,
		`Channels_1G.count=${channels1gCount}`,
		`Channels.in_acquisition=${channelsInAcquisition}`,
		'Channel.signal=1C',
		'',
		'; ─── acquisition (GPS L1 C/A) ───────────────────────────────────────',
		'Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition',
		'Acquisition_1C.item_type=gr_complex',
		'Acquisition_1C.coherent_integration_time_ms=1',
		'; pfa=0.01 (statistically-derived probability of false alarm; supersedes a',
		'; raw threshold and is the canonical doc value from my-first-fix).',
		'Acquisition_1C.pfa=0.01',
		'Acquisition_1C.doppler_max=10000',
		'Acquisition_1C.doppler_step=250',
		'Acquisition_1C.bit_transition_flag=false',
		'Acquisition_1C.max_dwells=1',
		'Acquisition_1C.blocking=true',
		'',
		'; ─── tracking ───────────────────────────────────────────────────────',
		'Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking',
		'Tracking_1C.item_type=gr_complex',
		'; pll_bw_hz=40 matches the my-first-fix canonical value (40 Hz PLL is the',
		'; established default; 50 Hz is the sp-block default; 30 is conservative).',
		'Tracking_1C.pll_bw_hz=40.0',
		'Tracking_1C.dll_bw_hz=4.0',
		'Tracking_1C.early_late_space_chips=0.5',
		'',
		'; ─── telemetry decoder ─────────────────────────────────────────────',
		'TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder',
		''
	];

	if (cfg.constellations === 'MULTI_L1') {
		lines.push(
			'; ─── Galileo E1 ────────────────────────────────────────────────────',
			'Acquisition_1B.implementation=Galileo_E1_PCPS_Ambiguous_Acquisition',
			'Acquisition_1B.item_type=gr_complex',
			'Acquisition_1B.threshold=0.015',
			'Acquisition_1B.doppler_max=10000',
			'Acquisition_1B.doppler_step=125',
			'Tracking_1B.implementation=Galileo_E1_DLL_PLL_VEML_Tracking',
			'TelemetryDecoder_1B.implementation=Galileo_E1B_Telemetry_Decoder',
			'',
			'; ─── GLONASS L1 C/A ────────────────────────────────────────────────',
			'Acquisition_1G.implementation=GLONASS_L1_CA_PCPS_Acquisition',
			'Acquisition_1G.item_type=gr_complex',
			'Acquisition_1G.threshold=0.01',
			'Acquisition_1G.doppler_max=10000',
			'Acquisition_1G.doppler_step=250',
			'Tracking_1G.implementation=GLONASS_L1_CA_DLL_PLL_Tracking',
			'TelemetryDecoder_1G.implementation=GLONASS_L1_CA_Telemetry_Decoder',
			''
		);
	}

	lines.push(
		'; ─── observables ────────────────────────────────────────────────────',
		'Observables.implementation=Hybrid_Observables',
		'',
		'; ─── PVT (RTKLIB engine; emits NMEA + RTCM for our consumers) ──────',
		'PVT.implementation=RTKLIB_PVT',
		'PVT.positioning_mode=Single',
		'PVT.iono_model=Broadcast',
		'PVT.trop_model=Saastamoinen',
		'PVT.output_rate_ms=100',
		'PVT.display_rate_ms=500',
		'PVT.flag_nmea_tty_port=false',
		`PVT.nmea_dump_filename=${GNSS_SDR_NMEA_FIFO}`,
		'PVT.nmea_dump_enabled=true',
		'PVT.flag_rtcm_server=true',
		'PVT.flag_rtcm_tty_port=false',
		`PVT.rtcm_tcp_port=${GNSS_SDR_RTCM_PORT}`,
		'PVT.rtcm_MT1019_rate_ms=5000',
		'PVT.rtcm_MT1045_rate_ms=5000',
		'PVT.rtcm_MT1077_rate_ms=1000',
		'PVT.rtcm_MT1097_rate_ms=1000',
		'PVT.output_enabled=false',
		'',
		'; ─── monitor (UDP protobuf telemetry, future panel) ────────────────',
		'Monitor.enable_monitor=true',
		'; Param name is `decimator_factor` not `decimation_factor` (verified against',
		'; canonical monitoring tutorial 2026-05-27). With observations at 20 ms,',
		'; decimator_factor=50 means one Monitor sample/sec into gnss-sdr-monitor.',
		'Monitor.decimator_factor=50',
		'Monitor.client_addresses=127.0.0.1',
		`Monitor.udp_port=${GNSS_SDR_MONITOR_UDP_PORT}`,
		'',
		'; ─── telecommand TCP/IP (runtime control: reset/standby/warmstart) ─',
		'; Requires the gnss-sdr-harness.sh wrapper to handle the exit-code-42',
		'; re-exec triggered by the `reset` command. The Argos backend opens a TCP',
		'; socket to localhost:3333, sends a one-word command + CRLF, reads the',
		'; OK/ERROR response back.',
		';',
		'; SECURITY NOTE: gnss-sdr v0.0.21 binds telecommand on 0.0.0.0 with no',
		'; bind-address config option (verified against',
		'; https://gnss-sdr.org/docs/sp-blocks/global-parameters/#telecommand-via-tcpip).',
		'; Argos deployments MUST block external access to TCP port 3333 via host',
		'; firewall (e.g. `iptables -I INPUT -p tcp ! -i lo --dport 3333 -j DROP`)',
		'; or kernel netns isolation. Tracking upstream feature request to add a',
		'; `GNSS-SDR.telecommand_listening_ip` key (filed 2026-05-27).',
		'GNSS-SDR.telecommand_enabled=true',
		'GNSS-SDR.telecommand_tcp_port=3333',
		''
	);

	return lines.join('\n');
}
