/**
 * Generate the `gnss-sdr.conf` consumed by `gnss-sdr --config_file=...`.
 *
 * Output cribs from the canonical upstream recipe at
 * `conf/RealTime_input/gnss-sdr_GPS_L1_USRP_realtime.conf` in the gnss-sdr
 * repo: an empty `SignalSource.device_address` lets UHD auto-discover the
 * B205mini over USB without us hard-coding a serial number.
 *
 * The default L1-only config matches Argos's user-locked plan decision
 * (2026-05-27): fastest first fix, ~70% CPU on Jetson Orin, the operator
 * opts into multi-constellation explicitly via the advanced form.
 */

import {
	type ConstellationSet,
	GNSS_SDR_CONF_DIR,
	GNSS_SDR_MONITOR_UDP_PORT,
	GNSS_SDR_NMEA_FIFO,
	GNSS_SDR_RTCM_PORT,
	type GnssSdrStartOptions
} from './gnss-sdr-vnc-types';

// B205mini hardware bounds — mirror of the file-local constants in
// src/lib/server/spectrum/b205-source.ts:46-47. Those are not exported, so we
// duplicate the (immutable, vendor-defined) values here rather than touch
// the spectrum module just for two consts.
const B205_MIN_FREQ_HZ = 70_000_000;
const B205_MAX_FREQ_HZ = 6_000_000_000;

/** GPS L1 carrier frequency in Hz. */
const GPS_L1_FREQ_HZ = 1_575_420_000;

/** B205mini ADC ceiling per the Ettus B2x0 manual. */
const B205_MAX_SAMPLE_RATE = 61_440_000;

const DEFAULT_SAMPLE_RATE_L1 = 4_000_000;
const DEFAULT_SAMPLE_RATE_MULTI = 8_000_000;
const DEFAULT_GAIN_DB = 50;
const MIN_GAIN_DB = 0;
const MAX_GAIN_DB = 76;

/** Path to the generated config file. */
export const GENERATED_CONF_PATH = `${GNSS_SDR_CONF_DIR}/gnss-sdr.conf`;

/** Resolved knobs after merging caller options with defaults. */
export interface ResolvedConfig {
	constellations: ConstellationSet;
	sampleRate: number;
	gain: number;
	freq: number;
}

/**
 * Resolve caller-supplied {@link GnssSdrStartOptions} against defaults and
 * validate against B205 hardware bounds. Pure — easy to unit-test.
 */
// eslint-disable-next-line complexity
export function resolveConfig(options: GnssSdrStartOptions = {}): ResolvedConfig {
	const constellations: ConstellationSet = options.constellations ?? 'L1_GPS_ONLY';
	const sampleRate =
		options.sampleRate ??
		(constellations === 'L1_GPS_ONLY' ? DEFAULT_SAMPLE_RATE_L1 : DEFAULT_SAMPLE_RATE_MULTI);
	const gain = options.gain ?? DEFAULT_GAIN_DB;

	if (GPS_L1_FREQ_HZ < B205_MIN_FREQ_HZ || GPS_L1_FREQ_HZ > B205_MAX_FREQ_HZ) {
		throw new Error(`GPS L1 frequency ${GPS_L1_FREQ_HZ} Hz outside B205 range`);
	}
	if (sampleRate <= 0 || sampleRate > B205_MAX_SAMPLE_RATE) {
		throw new Error(
			`sampleRate ${sampleRate} sps outside (0, ${B205_MAX_SAMPLE_RATE}] for B205mini`
		);
	}
	if (gain < MIN_GAIN_DB || gain > MAX_GAIN_DB) {
		throw new Error(
			`gain ${gain} dB outside [${MIN_GAIN_DB}, ${MAX_GAIN_DB}] for B205mini AD9364`
		);
	}

	return { constellations, sampleRate, gain, freq: GPS_L1_FREQ_HZ };
}

/**
 * Build the configuration text. Mirrors the canonical upstream USRP recipe
 * with Argos-specific overrides for the NMEA fifo and the gpsd-bridge RTCM
 * port. The PVT block emits NMEA to {@link GNSS_SDR_NMEA_FIFO}, which the
 * socat bridge tails and forwards to gpsd on TCP {@link GNSS_SDR_NMEA_BRIDGE_PORT}.
 */
// eslint-disable-next-line max-lines-per-function
export function generateGnssSdrConf(options: GnssSdrStartOptions = {}): string {
	const cfg = resolveConfig(options);
	const channels1cCount = 6;
	const channels1bCount = cfg.constellations === 'L1_GPS_ONLY' ? 0 : 4;
	const channels1gCount = cfg.constellations === 'L1_GPS_ONLY' ? 0 : 4;
	const internalFs = Math.min(cfg.sampleRate, 4_000_000);

	const lines: string[] = [
		'; gnss-sdr.conf — generated by Argos gnss-sdr-config-generator.ts. Do not edit by hand.',
		'[GNSS-SDR]',
		'',
		'; ─── global ────────────────────────────────────────────────────────',
		`GNSS-SDR.internal_fs_sps=${internalFs}`,
		'',
		'; ─── signal source — B205mini via UHD, auto-discovered over USB ────',
		'SignalSource.implementation=UHD_Signal_Source',
		"SignalSource.device_address=''",
		'SignalSource.item_type=gr_complex',
		`SignalSource.sampling_frequency=${cfg.sampleRate}`,
		`SignalSource.freq=${cfg.freq}`,
		`SignalSource.gain=${cfg.gain}`,
		'SignalSource.subdevice=A:0',
		'SignalSource.samples=0',
		'SignalSource.repeat=false',
		'SignalSource.enable_throttle_control=false',
		'',
		'; ─── conditioner (pass through; we already requested L1 baseband) ──',
		'SignalConditioner.implementation=Pass_Through',
		'',
		'; ─── channels ──────────────────────────────────────────────────────',
		`Channels_1C.count=${channels1cCount}`,
		`Channels_1B.count=${channels1bCount}`,
		`Channels_1G.count=${channels1gCount}`,
		'Channels.in_acquisition=1',
		'Channel.signal=1C',
		'',
		'; ─── acquisition (GPS L1 C/A) ───────────────────────────────────────',
		'Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition',
		'Acquisition_1C.item_type=gr_complex',
		'Acquisition_1C.coherent_integration_time_ms=1',
		'Acquisition_1C.threshold=0.01',
		'Acquisition_1C.doppler_max=10000',
		'Acquisition_1C.doppler_step=500',
		'Acquisition_1C.bit_transition_flag=false',
		'Acquisition_1C.max_dwells=1',
		'',
		'; ─── tracking ───────────────────────────────────────────────────────',
		'Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking',
		'Tracking_1C.item_type=gr_complex',
		'Tracking_1C.pll_bw_hz=30.0',
		'Tracking_1C.dll_bw_hz=4.0',
		'Tracking_1C.early_late_space_chips=0.5',
		'',
		'; ─── telemetry decoder ─────────────────────────────────────────────',
		'TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder',
		''
	];

	if (cfg.constellations === 'MULTI_L1') {
		lines.push(
			'; ─── Galileo E1 ────────────────────────────────────────────────────',
			'Acquisition_1B.implementation=Galileo_E1_PCPS_Ambiguous_Acquisition',
			'Acquisition_1B.item_type=gr_complex',
			'Acquisition_1B.threshold=0.015',
			'Acquisition_1B.doppler_max=10000',
			'Acquisition_1B.doppler_step=125',
			'Tracking_1B.implementation=Galileo_E1_DLL_PLL_VEML_Tracking',
			'TelemetryDecoder_1B.implementation=Galileo_E1B_Telemetry_Decoder',
			'',
			'; ─── GLONASS L1 C/A ────────────────────────────────────────────────',
			'Acquisition_1G.implementation=GLONASS_L1_CA_PCPS_Acquisition',
			'Acquisition_1G.item_type=gr_complex',
			'Acquisition_1G.threshold=0.01',
			'Acquisition_1G.doppler_max=10000',
			'Acquisition_1G.doppler_step=250',
			'Tracking_1G.implementation=GLONASS_L1_CA_DLL_PLL_Tracking',
			'TelemetryDecoder_1G.implementation=GLONASS_L1_CA_Telemetry_Decoder',
			''
		);
	}

	lines.push(
		'; ─── observables ────────────────────────────────────────────────────',
		'Observables.implementation=Hybrid_Observables',
		'',
		'; ─── PVT (RTKLIB engine; emits NMEA + RTCM for our consumers) ──────',
		'PVT.implementation=RTKLIB_PVT',
		'PVT.positioning_mode=Single',
		'PVT.iono_model=Broadcast',
		'PVT.trop_model=Saastamoinen',
		'PVT.output_rate_ms=100',
		'PVT.display_rate_ms=500',
		'PVT.flag_nmea_tty_port=false',
		`PVT.nmea_dump_filename=${GNSS_SDR_NMEA_FIFO}`,
		'PVT.nmea_dump_enabled=true',
		'PVT.flag_rtcm_server=true',
		'PVT.flag_rtcm_tty_port=false',
		`PVT.rtcm_tcp_port=${GNSS_SDR_RTCM_PORT}`,
		'PVT.rtcm_MT1019_rate_ms=5000',
		'PVT.rtcm_MT1045_rate_ms=5000',
		'PVT.rtcm_MT1077_rate_ms=1000',
		'PVT.rtcm_MT1097_rate_ms=1000',
		'PVT.output_enabled=false',
		'',
		'; ─── monitor (UDP protobuf telemetry, future panel) ────────────────',
		'Monitor.enable_monitor=true',
		'Monitor.decimation_factor=50',
		'Monitor.client_addresses=127.0.0.1',
		`Monitor.udp_port=${GNSS_SDR_MONITOR_UDP_PORT}`,
		''
	);

	return lines.join('\n');
}
