#!/usr/bin/env bash
# Module: sudoers drop-in for Argos runtime user, UHD kernel tuning,
# Jetson nvpmodel/jetson_clocks, B205 USB-speed diagnostic.
#
# Sourced by scripts/ops/install-dragonsync.sh — do not run directly.
# Depends on: ARGOS_USER, and the info/warn/err/step logging helpers.

[[ -n "${ARGOS_USER:-}" ]] || { echo "[_post.sh] must be sourced by install-dragonsync.sh" >&2; exit 1; }

# ─────────────────────────────────────────────────────────────────────────────
# 7. sudoers for Argos runtime user
# ─────────────────────────────────────────────────────────────────────────────

step "SUDOERS"

SUDOERS_TMP="/etc/sudoers.d/argos-dragonsync.new"
SUDOERS_FINAL="/etc/sudoers.d/argos-dragonsync"

cat > "$SUDOERS_TMP" <<EOF
# Argos — DragonSync / droneid-go / wardragon-fpv-detect lifecycle control
# Generated by scripts/ops/install-dragonsync.sh — do not edit by hand.
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start zmq-decoder.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop zmq-decoder.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl is-active zmq-decoder.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start dragonsync.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop dragonsync.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl is-active dragonsync.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start wardragon-fpv-detect.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop wardragon-fpv-detect.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl is-active wardragon-fpv-detect.service
# Phase 5: Argos C2 scanner (HackRF sub-GHz sweep)
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start argos-c2-scanner.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop argos-c2-scanner.service
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl is-active argos-c2-scanner.service
# Phase 2: SSE log streamer uses journalctl -f for the three services.
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/journalctl -u dragonsync -u zmq-decoder -u wardragon-fpv-detect -f --output=short-iso --no-pager
# Phase 5: SSE log streamer includes argos-c2-scanner when both scanners active
$ARGOS_USER ALL=(ALL) NOPASSWD: /usr/bin/journalctl -u dragonsync -u zmq-decoder -u wardragon-fpv-detect -u argos-c2-scanner -f --output=short-iso --no-pager
EOF
chmod 0440 "$SUDOERS_TMP"
if visudo -cf "$SUDOERS_TMP" >/dev/null; then
    mv "$SUDOERS_TMP" "$SUDOERS_FINAL"
    info "Installed $SUDOERS_FINAL"
else
    rm -f "$SUDOERS_TMP"
    err "sudoers syntax check failed — bailing."
fi

# ─────────────────────────────────────────────────────────────────────────────
# 7b. UHD / Jetson tuning (Phase 3 overflow remediation)
# Kernel socket buffers per UHD B210 troubleshooting guidance + Jetson-specific
# max-perf mode (nvpmodel -m 0, jetson_clocks). See plan Phase 3.
# ─────────────────────────────────────────────────────────────────────────────

step "UHD TUNING"

# Kernel socket buffers — sdrstore.eu B210 guide recommends 50 MB.
SYSCTL_FILE="/etc/sysctl.d/99-argos-uhd.conf"
cat > "$SYSCTL_FILE" <<EOF
# Argos UHD overflow remediation — 50 MB rx/tx socket buffers.
# Raised from jammy defaults (~212 KB) per sdrstore.eu B210 troubleshooting
# guide. Helps USRP B200-series sustain high sample rates without xhci drops.
net.core.rmem_max = 50000000
net.core.rmem_default = 50000000
net.core.wmem_max = 50000000
net.core.wmem_default = 50000000

# Argos SSE log-streamer — raise inotify watch limit so journalctl -f on three
# services can use inotify instead of falling back to polling. Symptom without
# this: the scan view shows 'Insufficient watch descriptors available.
# Reverting to -n.' and EventSource flaps on reconnect. Jetson default is
# 8192 which is quickly exhausted by journald + argos + chromium + editors.
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 512
EOF
chmod 0644 "$SYSCTL_FILE"
if sysctl --system >/dev/null 2>&1; then
    info "Applied kernel socket buffer tuning ($SYSCTL_FILE)."
else
    warn "sysctl --system returned non-zero; tuning may not take effect."
fi

# Jetson-specific max performance. On aarch64 Tegra, cpupower is unreliable;
# NVIDIA's own tools (nvpmodel + jetson_clocks) are authoritative.
if [[ -f /etc/nv_tegra_release ]]; then
    if command -v nvpmodel >/dev/null 2>&1; then
        if nvpmodel -m 0 >/dev/null 2>&1; then
            info "Set nvpmodel to MAXN (mode 0)."
        else
            warn "nvpmodel -m 0 failed; current mode preserved."
        fi
    fi
    if command -v jetson_clocks >/dev/null 2>&1; then
        if jetson_clocks >/dev/null 2>&1; then
            info "Pinned Jetson clocks to max (DVFS disabled)."
        else
            warn "jetson_clocks failed; DVFS throttling remains active."
        fi
    fi
else
    info "Non-Jetson host — skipping nvpmodel/jetson_clocks."
fi

# USB 3 SuperSpeed diagnostic — warn if B205 is on USB 2 (480M).
# Ettus USRP B200-series VID:PID 2500:0022
if lsusb -v -d 2500:0022 2>/dev/null | grep -q 'bcdUSB.*2\.\(00\|1\)'; then
    warn "B205mini is enumerating at USB 2 speed (480 Mbps)."
    warn "Sustained 8 Msps requires USB 3 SuperSpeed (5000 Mbps)."
    warn "Move the B205mini to a blue USB 3 port on the Jetson."
elif lsusb -t 2>/dev/null | awk '/Bus 02/,/Bus 01/' | grep -qE '5000M.*Vendor'; then
    info "B205mini on USB 3 SuperSpeed (5 Gbps) — OK."
fi
